FROM eclipse-temurin:17.0.10_7-jdk-jammy
ARG JAR_FILE=target/InvokeJsonPlaceholderRestSvc-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar
COPY application.yaml application.yaml
COPY application-env.yaml application-env.yaml
EXPOSE 8080
CMD ["java", "-jar", "-Dspring.profiles.active=env", "app.jar"]
