apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: springbootdemo
        imagePullPolicy: Always
        image: us-ashburn-1.ocir.io/idzor6zhmigm/oci-test:${{FD_PROJECT_VERSION}}
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: springboot-demo-config3
        - secretRef:
            name: springbootdemo-secret
      imagePullSecrets:
      - name: myregistrykey
